import { useTranslation } from './i18n';

// Copy shared by the new analytics and application screens. English phrases are
// the stable keys so the API can still return its documented metric identifiers.
const fr = {
  'Performance chart': 'Graphique de performance', 'Selected period': 'Période sélectionnée', 'Metric': 'Indicateur',
  'Decision intelligence': 'Aide à la décision', 'My dashboard': 'Mon tableau de bord',
  'Business performance and work needing attention · UTC reporting': 'Performance de l’activité et points à examiner · heures UTC',
  'Needs attention': 'À examiner', 'View all': 'Tout voir', 'Open report': 'Ouvrir le rapport',
  'No analytics domains are assigned to this account.': 'Aucun domaine d’analyse n’est attribué à ce compte.',
  'Important changes': 'Modifications importantes', 'Decision support': 'Aide à la décision',
  'Attention center': 'Centre d’attention', 'Findings use explicit thresholds and include their evidence.': 'Les constats reposent sur des seuils explicites et présentent leurs preuves.',
  'Domain analytics': 'Analyse par domaine', 'UTC reporting · immediately preceding equivalent period for comparisons': 'Heures UTC · comparaison avec la période précédente de même durée',
  'Commercial funnel': 'Entonnoir commercial', 'Hiring progression': 'Progression du recrutement', 'Source quality': 'Qualité des sources',
  'Largest observed stage drop:': 'Plus forte baisse observée entre étapes :',
  'entities). This is descriptive, not a causal finding.': 'entités). Ce constat est descriptif, sans conclusion causale.',
  'Subject intelligence': 'Analyse du sujet', 'Performance': 'Performance', 'Tracked journey': 'Parcours suivi', 'Admin changes': 'Modifications administrateur',
  'Performance metrics are unavailable for this subject type.': 'Les indicateurs de performance ne sont pas disponibles pour ce type de sujet.',
  'No tracked events in this period.': 'Aucun événement suivi sur cette période.',
  'Activity history requires the Activity Logs permission.': 'L’historique exige l’autorisation de consulter le journal d’activité.',
  'Subject explorer': 'Explorateur de sujets', 'Search': 'Rechercher', 'Type': 'Type', 'Results': 'Résultats',
  'Applications': 'Candidatures', 'Submitted candidates and hiring stages': 'Candidatures reçues et étapes de recrutement',
  'Application detail': 'Détails de la candidature', 'View intelligence': 'Voir l’analyse', 'Candidate': 'Candidat', 'Position': 'Poste',
  'Position unavailable': 'Poste indisponible', 'Email': 'E-mail', 'Phone': 'Téléphone', 'Submitted': 'Soumise', 'Source': 'Source',
  'Introduction': 'Présentation', 'Stage': 'Étape', 'Assignee': 'Responsable', 'Unassigned': 'Non attribuée',
  'Add note': 'Ajouter une note', 'Saving…': 'Enregistrement…', 'Save changes': 'Enregistrer les modifications',
  'Stage history': 'Historique des étapes', 'No stage history recorded.': 'Aucun historique enregistré.',
  'Notes': 'Notes', 'No notes recorded.': 'Aucune note enregistrée.', 'Pipeline': 'Pipeline',
  'Filter by stage': 'Filtrer par étape', 'All stages': 'Toutes les étapes', 'Inspect': 'Examiner',
  'Previous': 'Précédent', 'Next': 'Suivant', 'Page': 'Page', 'Applied': 'Date de candidature',
  'No data in this period.': 'Aucune donnée sur cette période.', 'Loading analytics': 'Chargement des analyses',
  'This section could not be loaded.': 'Impossible de charger cette section.', 'Retry': 'Réessayer',
  'Unavailable': 'Indisponible', 'vs previous period': 'par rapport à la période précédente',
  'Today': 'Aujourd’hui', '7 days': '7 jours', '30 days': '30 jours', '90 days': '90 jours', 'From': 'Du', 'To': 'Au',
  'Data quality': 'Qualité des données', 'Show evidence': 'Afficher les preuves', 'Hide evidence': 'Masquer les preuves',
  'No findings meet the current evidence thresholds.': 'Aucun constat ne satisfait les seuils de preuve actuels.',
  'No recorded admin changes in this period.': 'Aucune modification administrative enregistrée sur cette période.',
  'Admin': 'Administrateur', 'Product performance': 'Performance des produits', 'Campaigns': 'Campagnes',
  'Position performance': 'Performance des postes', 'Article performance': 'Performance des articles',
  'Loss reasons': 'Motifs de perte', 'Quotation status': 'Statut des devis', 'Details': 'Détails',
  'Product': 'Produit', 'Viewers': 'Visiteurs', 'Sales intent': 'Intention d’achat', 'Qualified': 'Qualifiés',
  'Won deals': 'Affaires gagnées', 'Conversion %': 'Conversion %', 'Revenue': 'Chiffre d’affaires',
  'Revenue trend': 'Tendance du chiffre d’affaires', 'Classification': 'Classement', 'Channel': 'Canal',
  'Campaign': 'Campagne', 'Creative': 'Création', 'Landing': 'Page d’arrivée', 'Device': 'Appareil',
  'Visitors': 'Visiteurs', 'Views': 'Vues', 'Apply clicks': 'Clics sur Postuler', 'Application rate %': 'Taux de candidature %',
  'Article': 'Article', 'Readers': 'Lecteurs', 'Reading progress %': 'Progression de lecture %',
  'Product clicks': 'Clics vers les produits', 'Product CTR %': 'Taux de clic produit %', 'Contact clicks': 'Clics de contact',
  'Loss reason': 'Motif de perte', 'Leads': 'Prospects', 'Count': 'Nombre', 'Status': 'Statut',
  'Qualified leads': 'Prospects qualifiés', 'Qualified leads / visitors': 'Prospects qualifiés / visiteurs',
  'Insufficient data': 'Données insuffisantes', 'No won deals in this period': 'Aucune affaire gagnée sur cette période',
  'No analytics data': 'Aucune donnée d’analyse', 'Attention Center': 'Centre d’attention', 'Acquisition': 'Acquisition',
  'Sales Analytics': 'Analyse des ventes', 'Product Analytics': 'Analyse des produits',
  'Hiring Analytics': 'Analyse du recrutement', 'Content Analytics': 'Analyse du contenu',
  'Operations Analytics': 'Analyse des opérations', 'Explorer': 'Explorateur',
  'Performance & activity': 'Performance et activité', 'Subject ID': 'Identifiant du sujet', 'Event name': 'Nom de l’événement',
  'Dashboard persona': 'Profil du tableau de bord',
  'Product image': 'Image du produit',
  'Application submitted. Thank you.': 'Candidature envoyée. Merci.', 'Full name': 'Nom complet',
  'Short introduction': 'Courte présentation', 'Submit application': 'Envoyer la candidature', 'Cancel': 'Annuler',
  'Sending…': 'Envoi…', 'Application could not be submitted. Please retry.': 'Impossible d’envoyer la candidature. Réessayez.',
};
const ar = {
  'Performance chart': 'مخطط الأداء', 'Selected period': 'الفترة المحددة', 'Metric': 'المؤشر',
  'Decision intelligence': 'تحليلات القرار', 'My dashboard': 'لوحتي',
  'Business performance and work needing attention · UTC reporting': 'أداء الأعمال والمهام التي تتطلب الانتباه · توقيت UTC',
  'Needs attention': 'يتطلب الانتباه', 'View all': 'عرض الكل', 'Open report': 'فتح التقرير',
  'No analytics domains are assigned to this account.': 'لم تُخصص مجالات تحليل لهذا الحساب.',
  'Important changes': 'تغييرات مهمة', 'Decision support': 'دعم القرار', 'Attention center': 'مركز الانتباه',
  'Findings use explicit thresholds and include their evidence.': 'تعتمد النتائج على حدود واضحة وتعرض أدلتها.',
  'Domain analytics': 'تحليلات المجال', 'UTC reporting · immediately preceding equivalent period for comparisons': 'توقيت UTC · المقارنة مع الفترة السابقة المماثلة',
  'Commercial funnel': 'قمع المبيعات', 'Hiring progression': 'مراحل التوظيف', 'Source quality': 'جودة المصادر',
  'Largest observed stage drop:': 'أكبر انخفاض مرصود بين المراحل:',
  'entities). This is descriptive, not a causal finding.': 'كيانات). هذه ملاحظة وصفية وليست استنتاجاً سببياً.',
  'Subject intelligence': 'تحليلات العنصر', 'Performance': 'الأداء', 'Tracked journey': 'المسار المتتبع', 'Admin changes': 'تغييرات المسؤولين',
  'Performance metrics are unavailable for this subject type.': 'مقاييس الأداء غير متاحة لهذا النوع من العناصر.',
  'No tracked events in this period.': 'لا توجد أحداث متتبعة في هذه الفترة.',
  'Activity history requires the Activity Logs permission.': 'يتطلب سجل النشاط صلاحية عرض سجلات النشاط.',
  'Subject explorer': 'مستكشف العناصر', 'Search': 'بحث', 'Type': 'النوع', 'Results': 'النتائج',
  'Applications': 'طلبات التوظيف', 'Submitted candidates and hiring stages': 'المرشحون المتقدمون ومراحل التوظيف',
  'Application detail': 'تفاصيل الطلب', 'View intelligence': 'عرض التحليلات', 'Candidate': 'المرشح', 'Position': 'الوظيفة',
  'Position unavailable': 'الوظيفة غير متاحة', 'Email': 'البريد الإلكتروني', 'Phone': 'الهاتف', 'Submitted': 'تاريخ التقديم', 'Source': 'المصدر',
  'Introduction': 'نبذة', 'Stage': 'المرحلة', 'Assignee': 'المسؤول', 'Unassigned': 'غير مسند',
  'Add note': 'إضافة ملاحظة', 'Saving…': 'جارٍ الحفظ…', 'Save changes': 'حفظ التغييرات',
  'Stage history': 'سجل المراحل', 'No stage history recorded.': 'لا يوجد سجل للمراحل.',
  'Notes': 'ملاحظات', 'No notes recorded.': 'لا توجد ملاحظات.', 'Pipeline': 'مسار التوظيف',
  'Filter by stage': 'تصفية حسب المرحلة', 'All stages': 'كل المراحل', 'Inspect': 'فحص',
  'Previous': 'السابق', 'Next': 'التالي', 'Page': 'الصفحة', 'Applied': 'تاريخ التقديم',
  'No data in this period.': 'لا توجد بيانات في هذه الفترة.', 'Loading analytics': 'جارٍ تحميل التحليلات',
  'This section could not be loaded.': 'تعذر تحميل هذا القسم.', 'Retry': 'إعادة المحاولة',
  'Unavailable': 'غير متاح', 'vs previous period': 'مقارنة بالفترة السابقة',
  'Today': 'اليوم', '7 days': '7 أيام', '30 days': '30 يوماً', '90 days': '90 يوماً', 'From': 'من', 'To': 'إلى',
  'Data quality': 'جودة البيانات', 'Show evidence': 'عرض الأدلة', 'Hide evidence': 'إخفاء الأدلة',
  'No findings meet the current evidence thresholds.': 'لا توجد نتائج تستوفي حدود الأدلة الحالية.',
  'No recorded admin changes in this period.': 'لا توجد تغييرات إدارية مسجلة في هذه الفترة.',
  'Admin': 'المسؤول', 'Product performance': 'أداء المنتجات', 'Campaigns': 'الحملات',
  'Position performance': 'أداء الوظائف', 'Article performance': 'أداء المقالات',
  'Loss reasons': 'أسباب خسارة الفرص', 'Quotation status': 'حالة عروض الأسعار', 'Details': 'التفاصيل',
  'Product': 'المنتج', 'Viewers': 'المشاهدون', 'Sales intent': 'نية الشراء', 'Qualified': 'المؤهلون',
  'Won deals': 'الصفقات الرابحة', 'Conversion %': 'التحويل %', 'Revenue': 'الإيرادات',
  'Revenue trend': 'اتجاه الإيرادات', 'Classification': 'التصنيف', 'Channel': 'القناة',
  'Campaign': 'الحملة', 'Creative': 'المحتوى الإعلاني', 'Landing': 'صفحة الوصول', 'Device': 'الجهاز',
  'Visitors': 'الزوار', 'Views': 'المشاهدات', 'Apply clicks': 'نقرات التقديم', 'Application rate %': 'معدل التقديم %',
  'Article': 'المقال', 'Readers': 'القراء', 'Reading progress %': 'تقدم القراءة %',
  'Product clicks': 'نقرات المنتج', 'Product CTR %': 'معدل نقر المنتج %', 'Contact clicks': 'نقرات التواصل',
  'Loss reason': 'سبب الخسارة', 'Leads': 'العملاء المحتملون', 'Count': 'العدد', 'Status': 'الحالة',
  'Qualified leads': 'عملاء محتملون مؤهلون', 'Qualified leads / visitors': 'المؤهلون / الزوار',
  'Insufficient data': 'بيانات غير كافية', 'No won deals in this period': 'لا صفقات رابحة في هذه الفترة',
  'No analytics data': 'لا توجد بيانات تحليلية', 'Attention Center': 'مركز الانتباه', 'Acquisition': 'الاكتساب',
  'Sales Analytics': 'تحليلات المبيعات', 'Product Analytics': 'تحليلات المنتجات',
  'Hiring Analytics': 'تحليلات التوظيف', 'Content Analytics': 'تحليلات المحتوى',
  'Operations Analytics': 'تحليلات العمليات', 'Explorer': 'المستكشف',
  'Performance & activity': 'الأداء والنشاط', 'Subject ID': 'معرّف العنصر', 'Event name': 'اسم الحدث',
  'Dashboard persona': 'نوع لوحة التحكم',
  'Product image': 'صورة المنتج',
  'Application submitted. Thank you.': 'تم إرسال طلب التوظيف. شكراً لك.', 'Full name': 'الاسم الكامل',
  'Short introduction': 'نبذة قصيرة', 'Submit application': 'إرسال الطلب', 'Cancel': 'إلغاء',
  'Sending…': 'جارٍ الإرسال…', 'Application could not be submitted. Please retry.': 'تعذر إرسال الطلب. حاول مجدداً.',
};

const frExtra = {
  Products: 'Produits', Sales: 'Ventes', Hiring: 'Recrutement', Content: 'Contenu', Operations: 'Opérations', Sessions: 'Sessions',
  'Revenue (DZD)': 'Chiffre d’affaires (DZD)', 'Attributed revenue (DZD)': 'Chiffre d’affaires attribué (DZD)',
  'Product viewers': 'Visiteurs des produits', 'Active products': 'Produits actifs', 'New leads': 'Nouveaux prospects',
  'Unassigned leads': 'Prospects non attribués', 'Follow-ups due': 'Relances en retard', 'Quotes sent': 'Devis envoyés',
  'Lost leads': 'Prospects perdus', 'Open pipeline (DZD)': 'Pipeline ouvert (DZD)', 'Average won value (DZD)': 'Valeur moyenne gagnée (DZD)',
  'Lead → qualified': 'Prospect → qualifié', 'Qualified → won': 'Qualifié → gagné', 'Visitor → lead': 'Visiteur → prospect',
  'Lead → won': 'Prospect → gagné', 'Open positions': 'Postes ouverts', 'Awaiting review': 'En attente d’examen',
  Shortlisted: 'Présélectionnés', Interviews: 'Entretiens', Offers: 'Offres', Hires: 'Embauches',
  'Published articles': 'Articles publiés', 'Stale leads': 'Prospects inactifs', 'Overdue follow-ups': 'Relances en retard',
  'Unassigned quotations': 'Devis non attribués', 'Job view → apply click %': 'Vue du poste → clic Postuler %',
  'Apply click → application %': 'Clic Postuler → candidature %', 'Application → shortlist %': 'Candidature → présélection %',
  'Shortlist → interview %': 'Présélection → entretien %', 'Interview → offer %': 'Entretien → offre %',
  'Offer → hire %': 'Offre → embauche %', 'from prior stage': 'depuis l’étape précédente',
  executive: 'Direction', 'product manager': 'Responsable produits', 'marketing manager': 'Responsable marketing',
  'product family': 'Famille de produits', 'admin user': 'Administrateur',
  'sales manager': 'Responsable commercial', 'hiring manager': 'Responsable recrutement',
  'content manager': 'Responsable contenu', 'operations manager': 'Responsable opérations', 'general admin': 'Administrateur général',
  applied: 'Candidature reçue', screening: 'Examen', shortlisted: 'Présélection', interview: 'Entretien',
  offer: 'Offre', hired: 'Embauché', rejected: 'Refusé', withdrawn: 'Retiré',
  winner: 'Produit performant', hidden_opportunity: 'Opportunité cachée', conversion_problem: 'Problème de conversion',
  low_priority: 'Priorité faible', insufficient_data: 'Données insuffisantes',
  'hidden opportunity': 'opportunité cachée', 'conversion problem': 'problème de conversion',
  'Demand and order conversion are both at or above the current product median.': 'La demande et la conversion sont au moins égales aux médianes actuelles des produits.',
  'Conversion is at or above the product median while traffic is below the median.': 'La conversion atteint la médiane des produits, mais le trafic est inférieur à la médiane.',
  'Traffic is at or above the product median while conversion is below it.': 'Le trafic atteint la médiane des produits, mais la conversion y est inférieure.',
  'Demand and conversion are both below the current product median.': 'La demande et la conversion sont inférieures aux médianes actuelles.',
  'Maintain or increase promotion.': 'Maintenir ou augmenter la promotion.',
  'Increase visibility or acquisition carefully.': 'Examiner prudemment la visibilité et l’acquisition.',
  'Investigate the page, offer, pricing, CTA, availability, and traffic quality.': 'Examiner la page, l’offre, le prix, les appels à l’action, la disponibilité et la qualité du trafic.',
  'Improve conversion before prioritizing acquisition.': 'Améliorer la conversion avant de donner priorité à l’acquisition.',
  'Follow-ups are overdue': 'Des relances sont en retard',
  'Open leads have a follow-up date before now.': 'Des prospects ouverts ont une date de relance passée.',
  'Review the overdue lead queue.': 'Examiner la liste des relances en retard.',
  'No submitted internal applications were recorded for this published role in the selected period.': 'Aucune candidature interne reçue pour ce poste publié sur la période choisie.',
  'Review the role details and application flow.': 'Examiner la fiche du poste et le parcours de candidature.',
  'Readers did not trigger tracked product or contact actions in this period.': 'Les lecteurs n’ont déclenché aucune action suivie vers un produit ou le contact sur cette période.',
  'Review the article calls to action.': 'Examiner les appels à l’action de l’article.',
  'has views but no applications': 'a des vues, mais aucune candidature',
  'has readers but no tracked actions': 'a des lecteurs, mais aucune action suivie',
  'Observed stages': 'Étapes observées', 'Inquiry starts': 'Demandes commencées',
  'These counts are not a verified person-level cohort.': 'Ces nombres ne constituent pas une cohorte individuelle vérifiée.',
};
const arExtra = {
  Products: 'المنتجات', Sales: 'المبيعات', Hiring: 'التوظيف', Content: 'المحتوى', Operations: 'العمليات', Sessions: 'الجلسات',
  'Revenue (DZD)': 'الإيرادات (دج)', 'Attributed revenue (DZD)': 'الإيرادات المنسوبة (دج)',
  'Product viewers': 'مشاهدو المنتجات', 'Active products': 'المنتجات النشطة', 'New leads': 'العملاء المحتملون الجدد',
  'Unassigned leads': 'عملاء محتملون غير مسندين', 'Follow-ups due': 'متابعات متأخرة', 'Quotes sent': 'عروض أسعار مرسلة',
  'Lost leads': 'فرص ضائعة', 'Open pipeline (DZD)': 'الفرص المفتوحة (دج)', 'Average won value (DZD)': 'متوسط قيمة الصفقات الرابحة (دج)',
  'Lead → qualified': 'محتمل ← مؤهل', 'Qualified → won': 'مؤهل ← رابح', 'Visitor → lead': 'زائر ← محتمل',
  'Lead → won': 'محتمل ← رابح', 'Open positions': 'وظائف مفتوحة', 'Awaiting review': 'بانتظار المراجعة',
  Shortlisted: 'القائمة المختصرة', Interviews: 'المقابلات', Offers: 'العروض', Hires: 'التعيينات',
  'Published articles': 'مقالات منشورة', 'Stale leads': 'فرص غير نشطة', 'Overdue follow-ups': 'متابعات متأخرة',
  'Unassigned quotations': 'عروض أسعار غير مسندة', 'Job view → apply click %': 'مشاهدة الوظيفة ← نقر التقديم %',
  'Apply click → application %': 'نقر التقديم ← الطلب %', 'Application → shortlist %': 'الطلب ← القائمة المختصرة %',
  'Shortlist → interview %': 'القائمة المختصرة ← المقابلة %', 'Interview → offer %': 'المقابلة ← العرض %',
  'Offer → hire %': 'العرض ← التعيين %', 'from prior stage': 'من المرحلة السابقة',
  executive: 'الإدارة التنفيذية', 'product manager': 'مدير المنتجات', 'marketing manager': 'مدير التسويق',
  'product family': 'عائلة المنتجات', 'admin user': 'مستخدم إداري',
  'sales manager': 'مدير المبيعات', 'hiring manager': 'مدير التوظيف',
  'content manager': 'مدير المحتوى', 'operations manager': 'مدير العمليات', 'general admin': 'مسؤول عام',
  applied: 'تم التقديم', screening: 'فحص', shortlisted: 'قائمة مختصرة', interview: 'مقابلة',
  offer: 'عرض', hired: 'تم التعيين', rejected: 'مرفوض', withdrawn: 'منسحب',
  winner: 'منتج ناجح', hidden_opportunity: 'فرصة مخفية', conversion_problem: 'مشكلة تحويل',
  low_priority: 'أولوية منخفضة', insufficient_data: 'بيانات غير كافية',
  'hidden opportunity': 'فرصة مخفية', 'conversion problem': 'مشكلة تحويل',
  'Demand and order conversion are both at or above the current product median.': 'الطلب والتحويل يساويان أو يفوقان وسيط المنتجات الحالي.',
  'Conversion is at or above the product median while traffic is below the median.': 'التحويل عند وسيط المنتجات أو فوقه، لكن الزيارات دونه.',
  'Traffic is at or above the product median while conversion is below it.': 'الزيارات عند وسيط المنتجات أو فوقه، لكن التحويل دونه.',
  'Demand and conversion are both below the current product median.': 'الطلب والتحويل كلاهما أقل من وسيط المنتجات الحالي.',
  'Maintain or increase promotion.': 'الحفاظ على الترويج أو زيادته.',
  'Increase visibility or acquisition carefully.': 'مراجعة الظهور والاكتساب بحذر.',
  'Investigate the page, offer, pricing, CTA, availability, and traffic quality.': 'مراجعة الصفحة والعرض والسعر والدعوات إلى الإجراء والتوفر وجودة الزيارات.',
  'Improve conversion before prioritizing acquisition.': 'تحسين التحويل قبل إعطاء الأولوية للاكتساب.',
  'Follow-ups are overdue': 'توجد متابعات متأخرة',
  'Open leads have a follow-up date before now.': 'لبعض الفرص المفتوحة موعد متابعة مضى.',
  'Review the overdue lead queue.': 'مراجعة قائمة المتابعات المتأخرة.',
  'No submitted internal applications were recorded for this published role in the selected period.': 'لم تُسجل طلبات توظيف داخلية لهذه الوظيفة المنشورة في الفترة المحددة.',
  'Review the role details and application flow.': 'مراجعة تفاصيل الوظيفة ومسار التقديم.',
  'Readers did not trigger tracked product or contact actions in this period.': 'لم يقم القراء بإجراءات متتبعة تجاه المنتجات أو التواصل في هذه الفترة.',
  'Review the article calls to action.': 'مراجعة دعوات المقال إلى الإجراء.',
  'has views but no applications': 'لديها مشاهدات دون طلبات توظيف',
  'has readers but no tracked actions': 'له قراء دون إجراءات متتبعة',
  'Observed stages': 'المراحل المرصودة', 'Inquiry starts': 'بدء الاستفسار',
  'These counts are not a verified person-level cohort.': 'هذه الأعداد لا تمثل مجموعة أفراد متحققة.',
};

const shippingFr = {
  'Edit Shipping Prices': 'Modifier les frais de livraison',
  'Configure Noest rates by wilaya, commune, and delivery method. Blank prices are unavailable.': 'Configurez les tarifs Noest par wilaya, commune et mode de livraison. Un tarif vide est indisponible.',
  'Export CSV for the import template; use one row per commune and pickup office.': 'Exportez le CSV comme modèle d’import ; utilisez une ligne par commune et bureau de retrait.',
  Reload: 'Actualiser', 'Export CSV': 'Exporter CSV', 'Import CSV': 'Importer CSV', 'Save all': 'Tout enregistrer',
  'Save wilaya': 'Enregistrer la wilaya', 'Search wilayas': 'Rechercher une wilaya', 'No wilayas configured.': 'Aucune wilaya configurée.',
  'Add wilaya': 'Ajouter une wilaya', Code: 'Code', Name: 'Nom', 'Add commune': 'Ajouter une commune',
  'Commune code': 'Code commune', 'Commune name': 'Nom commune', 'Communes and overrides': 'Communes et tarifs particuliers',
  'Home price (DA)': 'Tarif domicile (DA)', 'Stop Desk price (DA)': 'Tarif Stop Desk (DA)',
  'Home override (DA)': 'Tarif domicile particulier (DA)', 'Stop Desk override (DA)': 'Tarif Stop Desk particulier (DA)',
  'Home available': 'Livraison à domicile disponible', 'Stop Desk available': 'Stop Desk disponible',
  'Pickup offices': 'Bureaux de retrait', Available: 'Disponible', Remove: 'Supprimer',
  'Office code': 'Code bureau', 'Office name': 'Nom bureau', Address: 'Adresse', 'Add office': 'Ajouter un bureau',
  'Select a wilaya or import a CSV tariff list.': 'Sélectionnez une wilaya ou importez une liste CSV de tarifs.',
  'Apply validated import': 'Appliquer l’import validé', Cancel: 'Annuler', 'wilayas ready to import.': 'wilayas prêtes à importer.',
  'wilayas validated. Review and apply the import.': 'wilayas validées. Vérifiez puis appliquez l’import.',
  'Shipping tariff saved.': 'Tarif de livraison enregistré.', 'All shipping tariffs saved.': 'Tous les tarifs de livraison sont enregistrés.',
  'CSV import applied.': 'Import CSV appliqué.', 'Could not load shipping tariffs.': 'Impossible de charger les tarifs de livraison.',
  'Could not save shipping tariff.': 'Impossible d’enregistrer le tarif.', 'Could not save shipping tariffs.': 'Impossible d’enregistrer les tarifs.',
  'Could not import CSV.': 'Impossible d’importer le CSV.', 'Enter a unique wilaya code and name.': 'Saisissez un code et un nom de wilaya uniques.',
  'Enter a unique commune code and name.': 'Saisissez un code et un nom de commune uniques.',
  'Enter a unique office code and name.': 'Saisissez un code et un nom de bureau uniques.',
};
const shippingAr = {
  'Edit Shipping Prices': 'تعديل أسعار التوصيل',
  'Configure Noest rates by wilaya, commune, and delivery method. Blank prices are unavailable.': 'اضبط أسعار نوست حسب الولاية والبلدية وطريقة التوصيل. السعر الفارغ غير متاح.',
  'Export CSV for the import template; use one row per commune and pickup office.': 'صدّر CSV للحصول على نموذج الاستيراد؛ استخدم صفاً لكل بلدية ومكتب استلام.',
  Reload: 'تحديث', 'Export CSV': 'تصدير CSV', 'Import CSV': 'استيراد CSV', 'Save all': 'حفظ الكل',
  'Save wilaya': 'حفظ الولاية', 'Search wilayas': 'البحث عن ولاية', 'No wilayas configured.': 'لم تُضبط أي ولاية.',
  'Add wilaya': 'إضافة ولاية', Code: 'الرمز', Name: 'الاسم', 'Add commune': 'إضافة بلدية',
  'Commune code': 'رمز البلدية', 'Commune name': 'اسم البلدية', 'Communes and overrides': 'البلديات والأسعار الخاصة',
  'Home price (DA)': 'سعر التوصيل للمنزل (دج)', 'Stop Desk price (DA)': 'سعر مكتب الاستلام (دج)',
  'Home override (DA)': 'سعر المنزل الخاص (دج)', 'Stop Desk override (DA)': 'سعر المكتب الخاص (دج)',
  'Home available': 'التوصيل للمنزل متاح', 'Stop Desk available': 'الاستلام من المكتب متاح',
  'Pickup offices': 'مكاتب الاستلام', Available: 'متاح', Remove: 'إزالة',
  'Office code': 'رمز المكتب', 'Office name': 'اسم المكتب', Address: 'العنوان', 'Add office': 'إضافة مكتب',
  'Select a wilaya or import a CSV tariff list.': 'اختر ولاية أو استورد قائمة أسعار CSV.',
  'Apply validated import': 'تطبيق الاستيراد المتحقق منه', Cancel: 'إلغاء', 'wilayas ready to import.': 'ولايات جاهزة للاستيراد.',
  'wilayas validated. Review and apply the import.': 'ولايات تم التحقق منها. راجع الاستيراد ثم طبقه.',
  'Shipping tariff saved.': 'تم حفظ سعر التوصيل.', 'All shipping tariffs saved.': 'تم حفظ جميع أسعار التوصيل.',
  'CSV import applied.': 'تم تطبيق استيراد CSV.', 'Could not load shipping tariffs.': 'تعذر تحميل أسعار التوصيل.',
  'Could not save shipping tariff.': 'تعذر حفظ السعر.', 'Could not save shipping tariffs.': 'تعذر حفظ الأسعار.',
  'Could not import CSV.': 'تعذر استيراد CSV.', 'Enter a unique wilaya code and name.': 'أدخل رمز ولاية واسماً فريدين.',
  'Enter a unique commune code and name.': 'أدخل رمز بلدية واسماً فريدين.',
  'Enter a unique office code and name.': 'أدخل رمز مكتب واسماً فريدين.',
};

export function useIntelligenceCopy() {
  const lang = useTranslation()?.lang || 'en';
  return phrase => (lang === 'fr' ? shippingFr[phrase] || fr[phrase] || frExtra[phrase] : lang === 'ar' ? shippingAr[phrase] || ar[phrase] || arExtra[phrase] : null) || phrase;
}
